name: mobile
description: "My AREA mobile APP."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.8
  flutter_secure_storage: ^8.0.0
  webview_flutter: ^4.2.2
  provider: ^6.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/app_icon.png
    - assets/icons/google.png
    - assets/icons/X.png
    - assets/icons/email.png
    - assets/icons/facebook.png
    - assets/icons/spotify.png
    - assets/icons/FR.png
    - assets/icons/UK.png
    - assets/icons/avatar.png
    - assets/icons/github.png
    - assets/icons/discord.png
    - assets/icons/notion.png
    - assets/icons/reddit.png
    - assets/icons/date.png
    - assets/icons/microsoft.png
    - assets/icons/outlook.png
    - assets/icons/twitch.png
    - assets/icons/linkedin.png
    - assets/icons/baptiste.png
    - assets/icons/isma.png
    - assets/icons/sephorah.png
    - assets/icons/yass.png
    - assets/icons/gmail.png
    - assets/icons/weatherTime.png
    - assets/icons/coinFlip.png
    - assets/icons/islamic_prayer.png
    - assets/lang/en.json
    - assets/lang/fr.json

  fonts:
    - family: Murecho
      fonts:
        - asset: assets/fonts/Murecho-Regular.ttf
        - asset: assets/fonts/Murecho-Bold.ttf
        - asset: assets/fonts/Murecho-SemiBold.ttf
        - asset: assets/fonts/Murecho-Medium.ttf
          weight: 500
